In [52]:

import pandas as pd
import numpy as np

data = pd.read_csv('data/report14-18.txt', delimiter='\t')
data.head()

,기간,자치구,합계,합계.1,살인,살인.1,강도,강도.1,강간강제추행,강간강제추행.1,절도,절도.1,폭력,폭력.1
0,기간,자치구,발생,검거,발생,검거,발생,검거,발생,검거,발생,검거,발생,검거
1,2014,합계,"130,674","79,061",158,152,343,299,"5,462","4,957","59,393","19,120","65,318","54,533"
2,2014,종로구,"5,021","4,610",3,7,12,15,226,948,"2,272","1,281","2,508","2,359"
3,2014,중구,"5,231","3,188",6,5,13,13,221,161,"2,576",887,"2,415","2,122"
4,2014,용산구,"3,799","2,340",1,2,7,7,213,169,"1,560",522,"2,018","1,640"

In [53]:
# data['살인검거율'] = int(data['살인.1'])/int(data['살인']) * 100

data.dtypes # 데이터 타입 확인

기간          object
자치구         object
합계          object
합계.1        object
살인          object
살인.1        object
강도          object
강도.1        object
강간강제추행      object
강간강제추행.1    object
절도          object
절도.1        object
폭력          object
폭력.1        object
dtype: object

In [54]:
# 데이터에서 ,를 제거
for i in list(data.columns[2:]):
    data[i] = data[i].str.replace(',','')

data

,기간,자치구,합계,합계.1,살인,살인.1,강도,강도.1,강간강제추행,강간강제추행.1,절도,절도.1,폭력,폭력.1
0,기간,자치구,발생,검거,발생,검거,발생,검거,발생,검거,발생,검거,발생,검거
1,2014,합계,130674,79061,158,152,343,299,5462,4957,59393,19120,65318,54533
2,2014,종로구,5021,4610,3,7,12,15,226,948,2272,1281,2508,2359
3,2014,중구,5231,3188,6,5,13,13,221,161,2576,887,2415,2122
4,2014,용산구,3799,2340,1,2,7,7,213,169,1560,522,2018,1640
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,2018,관악구,5026,3653,9,9,10,12,352,305,2012,1025,2643,2302
127,2018,서초구,4726,3183,5,5,5,5,470,315,1851,838,2395,2020
128,2018,강남구,7513,5196,10,13,14,10,600,523,3004,1317,3885,3333
129,2018,송파구,5807,4051,5,6,6,8,309,254,2352,1034,3135,2749
130,2018,강동구,3919,2789,3,3,7,7,170,143,1515,765,2224,1871

In [55]:
# 0번째 행을 삭제
data = data.drop(data.index[0])
data.head()

,기간,자치구,합계,합계.1,살인,살인.1,강도,강도.1,강간강제추행,강간강제추행.1,절도,절도.1,폭력,폭력.1
1,2014,합계,130674,79061,158,152,343,299,5462,4957,59393,19120,65318,54533
2,2014,종로구,5021,4610,3,7,12,15,226,948,2272,1281,2508,2359
3,2014,중구,5231,3188,6,5,13,13,221,161,2576,887,2415,2122
4,2014,용산구,3799,2340,1,2,7,7,213,169,1560,522,2018,1640
5,2014,성동구,3582,2048,1,1,5,6,141,103,1753,529,1682,1409

In [64]:
# 타입을 실수로 바꾸어 주기
data = data.astype({'합계':'float','합계.1':'float','살인':'float','살인.1':'float',\
             '강도':'float','강도.1':'float', '강간강제추행':'float','강간강제추행.1':'float'\
             ,'절도':'float','절도.1':'float','폭력':'float','폭력.1':'float'})

In [66]:
# 실수로 바꿈
data.dtypes # 데이터 타입 확인

기간           object
자치구          object
합계          float64
합계.1        float64
살인          float64
살인.1        float64
강도          float64
강도.1        float64
강간강제추행      float64
강간강제추행.1    float64
절도          float64
절도.1        float64
폭력          float64
폭력.1        float64
dtype: object

In [72]:
# 범죄 검거율
data['범죄검거율'] = round(data['합계.1']/data['합계']*100,1)
data['범죄검거율']

1      60.5
2      91.8
3      60.9
4      61.6
5      57.2
       ...
126    72.7
127    67.4
128    69.2
129    69.8
130    71.2
Name: 범죄검거율, Length: 130, dtype: float64

In [125]:
# del data['살인검거율']
# data['살인'].groupby(data['자치구'])
# data['강도'].groupby(data['자치구'])

# 발생 건수만 뽑음
occur = data.loc[:,['자치구','살인', '강도', '강간강제추행', '절도','폭력','합계','합계.1']]
occur = occur.groupby(['자치구']).sum()
print(occur.shape)
occur

(26, 7)

         살인      강도   강간강제추행        절도        폭력        합계      합계.1
자치구
강남구    48.0   131.0   2684.0   17466.0   20521.0   40850.0   27416.0
강동구    21.0    47.0    806.0    9705.0   12699.0   23278.0   15763.0
강북구    36.0    54.0    955.0    6276.0   12025.0   19346.0   14809.0
강서구    46.0    42.0   1336.0   10001.0   14663.0   26088.0   18908.0
관악구    39.0    66.0   1734.0   11829.0   15687.0   29355.0   19145.0
광진구    29.0    56.0   1258.0   12818.0   11899.0   26060.0   16628.0
구로구    35.0    56.0   1384.0   10064.0   14567.0   26106.0   16977.0
금천구    27.0    34.0    928.0    6692.0   10145.0   17826.0   13125.0
노원구    29.0    35.0    903.0    9414.0   12820.0   23201.0   15361.0
도봉구    14.0    33.0    614.0    4693.0    7120.0   12474.0    9144.0
동대문구   35.0    44.0    814.0    8724.0   11908.0   21525.0   15952.0
동작구    19.0    39.0   1497.0    7255.0    8790.0   17600.0   11201.0
마포구    25.0    54.0   1931.0   11950.0   13957.0   27917.0   17572.0
서대문구   20.0    18.0    922.0    7490.0    9353.0   17803.0   12036.0
서초구    33.0    54.0   2046.0   11250.0   12042.0   25425.0   16414.0
성동구    12.0    25.0    629.0    6727.0    7797.0   15190.0   10381.0
성북구    31.0    38.0    825.0    7893.0   10193.0   18980.0   13185.0
송파구    40.0    44.0   1306.0   14607.0   16258.0   32255.0   20076.0
양천구    18.0    31.0    638.0    8641.0   11351.0   20679.0   13381.0
영등포구   73.0    64.0   1747.0   12981.0   17136.0   32001.0   20359.0
용산구    12.0    38.0   1316.0    7048.0   10813.0   19227.0   13137.0
은평구    28.0    47.0    928.0    8597.0   12550.0   22150.0   15915.0
종로구    28.0    48.0   1164.0    9523.0   11169.0   21932.0   21688.0
중구     15.0    50.0   1063.0   10975.0   10880.0   22983.0   14728.0
중랑구    41.0    45.0    860.0    9275.0   14225.0   24446.0   17213.0
합계    754.0  1193.0  30288.0  241894.0  310568.0  584697.0  400514.0

In [126]:
# 범죄검거율 
occur['검거율'] = round(occur['합계.1']/occur['합계']*100,1)
occur.head()

       살인     강도  강간강제추행       절도       폭력       합계     합계.1   검거율
자치구
강남구  48.0  131.0  2684.0  17466.0  20521.0  40850.0  27416.0  67.1
강동구  21.0   47.0   806.0   9705.0  12699.0  23278.0  15763.0  67.7
강북구  36.0   54.0   955.0   6276.0  12025.0  19346.0  14809.0  76.5
강서구  46.0   42.0  1336.0  10001.0  14663.0  26088.0  18908.0  72.5
관악구  39.0   66.0  1734.0  11829.0  15687.0  29355.0  19145.0  65.2

In [131]:
# column 이름 바꾸기
occur_arrest = occur.rename(columns={'합계':'발생합계', '합계.1':'검거합계'})
occur_arrest

         살인      강도   강간강제추행        절도        폭력      발생합계      검거합계   검거율
자치구
강남구    48.0   131.0   2684.0   17466.0   20521.0   40850.0   27416.0  67.1
강동구    21.0    47.0    806.0    9705.0   12699.0   23278.0   15763.0  67.7
강북구    36.0    54.0    955.0    6276.0   12025.0   19346.0   14809.0  76.5
강서구    46.0    42.0   1336.0   10001.0   14663.0   26088.0   18908.0  72.5
관악구    39.0    66.0   1734.0   11829.0   15687.0   29355.0   19145.0  65.2
광진구    29.0    56.0   1258.0   12818.0   11899.0   26060.0   16628.0  63.8
구로구    35.0    56.0   1384.0   10064.0   14567.0   26106.0   16977.0  65.0
금천구    27.0    34.0    928.0    6692.0   10145.0   17826.0   13125.0  73.6
노원구    29.0    35.0    903.0    9414.0   12820.0   23201.0   15361.0  66.2
도봉구    14.0    33.0    614.0    4693.0    7120.0   12474.0    9144.0  73.3
동대문구   35.0    44.0    814.0    8724.0   11908.0   21525.0   15952.0  74.1
동작구    19.0    39.0   1497.0    7255.0    8790.0   17600.0   11201.0  63.6
마포구    25.0    54.0   1931.0   11950.0   13957.0   27917.0   17572.0  62.9
서대문구   20.0    18.0    922.0    7490.0    9353.0   17803.0   12036.0  67.6
서초구    33.0    54.0   2046.0   11250.0   12042.0   25425.0   16414.0  64.6
성동구    12.0    25.0    629.0    6727.0    7797.0   15190.0   10381.0  68.3
성북구    31.0    38.0    825.0    7893.0   10193.0   18980.0   13185.0  69.5
송파구    40.0    44.0   1306.0   14607.0   16258.0   32255.0   20076.0  62.2
양천구    18.0    31.0    638.0    8641.0   11351.0   20679.0   13381.0  64.7
영등포구   73.0    64.0   1747.0   12981.0   17136.0   32001.0   20359.0  63.6
용산구    12.0    38.0   1316.0    7048.0   10813.0   19227.0   13137.0  68.3
은평구    28.0    47.0    928.0    8597.0   12550.0   22150.0   15915.0  71.9
종로구    28.0    48.0   1164.0    9523.0   11169.0   21932.0   21688.0  98.9
중구     15.0    50.0   1063.0   10975.0   10880.0   22983.0   14728.0  64.1
중랑구    41.0    45.0    860.0    9275.0   14225.0   24446.0   17213.0  70.4
합계    754.0  1193.0  30288.0  241894.0  310568.0  584697.0  400514.0  68.5

In [132]:
# txt파일로 저장
occur_arrest.to_csv('data/crime_in_seoul.csv', mode='w')